# Generated by Django 5.0.4 on 2024-07-05 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=250, null=True)),
                ('last_name', models.CharField(max_length=250, null=True)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('permanent_address', models.CharField(blank=True, max_length=250, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=250, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('place_of_birth', models.CharField(blank=True, max_length=250, null=True)),
                ('civil_status', models.CharField(blank=True, max_length=250, null=True)),
                ('sex', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('height', models.CharField(blank=True, max_length=20, null=True)),
                ('weight', models.CharField(blank=True, max_length=20, null=True)),
                ('bloodtype', models.CharField(blank=True, max_length=250, null=True)),
                ('citizenship', models.CharField(blank=True, max_length=250, null=True)),
                ('gsis', models.CharField(blank=True, max_length=20, null=True)),
                ('pag_ibig_no', models.CharField(blank=True, max_length=20, null=True)),
                ('philhealth', models.CharField(blank=True, max_length=20, null=True)),
                ('sss', models.CharField(blank=True, max_length=20, null=True)),
                ('tin', models.CharField(blank=True, max_length=20, null=True)),
                ('agency_employee_no', models.CharField(blank=True, max_length=20, null=True)),
                ('occupation', models.CharField(blank=True, max_length=250, null=True)),
                ('employee_business', models.CharField(blank=True, max_length=250, null=True)),
                ('business_address', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
