# Generated by Django 5.0.4 on 2024-07-08 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_item_children_date_of_birth_item_children_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='mobile_no',
        ),
        migrations.RemoveField(
            model_name='item',
            name='telephone_no',
        ),
        migrations.AlterField(
            model_name='item',
            name='email',
            field=models.EmailField(blank=True, max_length=250, null=True),
        ),
    ]
